name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - run: cd C:\dev\vcpkg && dir
      - run: cd C:\dev\vcpkg\installed\x64-windows\bin && dir


# C:\hostedtoolcache\windows\Python\3.8.6\x64\include