name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: choco install mingw --x86
      - uses: ilammy/msvc-dev-cmd@v1
      - run: i686-w64-mingw32-gcc -m32 main.c
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: .

# C:\hostedtoolcache\windows\Python\3.8.6\x64\include