name: test
on: [push]
jobs:
  test:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: python3 -m pip install secrethub
      - run: python3 test.py


# C:\hostedtoolcache\windows\Python\3.8.6\x64\include