name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: secrethub://secrethub/xgo/python/test-pypi/api-token


# C:\hostedtoolcache\windows\Python\3.8.6\x64\include