name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: ls /opt/hostedtoolcache/Python/3.9.0/x64/include

# C:\hostedtoolcache\windows\Python\3.8.6\x64\include