name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ls | grep -v test | xargs rm
        shell: bash


# C:\hostedtoolcache\windows\Python\3.8.6\x64\include