name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cd C:\ && dir -s *python*.lib

# C:\hostedtoolcache\windows\Python\3.8.6\x64\include