name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cd C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64 && dir
      - run: cd C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64 && tree

# C:\hostedtoolcache\windows\Python\3.8.6\x64\include