name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - run: cd C:\hostedtoolcache\ && dir
      - run: cd C:\hostedtoolcache\swig && dir


# C:\hostedtoolcache\windows\Python\3.8.6\x64\include